language: scala

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier

script: sbt scalafmtSbtCheck scalafmtCheckAll test

# whitelist only master branch and tags
branches:
  only:
    - master
